/**
 * Date and display helpers for the agenda surfaces (MON-213).
 *
 * Kept out of the page components so the window arithmetic and the
 * summary/objet fallback are unit-testable without rendering React, and so
 * `/agenda` and the homepage teaser cannot drift apart on either.
 *
 * Everything is computed in `Europe/Paris`: the sitting calendar is a Paris
 * calendar, and the server rendering it runs in UTC. Without the explicit
 * zone, a 21h séance would land on the previous day for a slice of the
 * evening and "cette semaine" would roll over at 01:00 Paris time.
 */

import type { AgendaItem } from './api'

export const PARIS_TZ = 'Europe/Paris'

/** How far ahead the empty state looks for the next sitting day. */
export const LOOKAHEAD_DAYS = 60

/** Items the homepage teaser shows before deferring to `/agenda`. */
export const HOME_TEASER_ITEMS = 3

const ISO_DATE = new Intl.DateTimeFormat('en-CA', {
  timeZone: PARIS_TZ,
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
})

const TIME = new Intl.DateTimeFormat('fr-FR', {
  timeZone: PARIS_TZ,
  hour: '2-digit',
  minute: '2-digit',
})

const LONG_DAY = new Intl.DateTimeFormat('fr-FR', {
  timeZone: 'UTC',
  weekday: 'long',
  day: 'numeric',
  month: 'long',
  year: 'numeric',
})

const SHORT_DAY = new Intl.DateTimeFormat('fr-FR', {
  timeZone: 'UTC',
  weekday: 'long',
  day: 'numeric',
  month: 'long',
})

/** Today's date in Paris, as the `YYYY-MM-DD` the API's `from`/`to` expect. */
export function parisToday(now: Date = new Date()): string {
  return ISO_DATE.format(now)
}

/** `YYYY-MM-DD` plus `days`, staying in plain-date arithmetic (no DST drift). */
export function addDays(isoDate: string, days: number): string {
  const shifted = new Date(`${isoDate}T00:00:00Z`)
  shifted.setUTCDate(shifted.getUTCDate() + days)
  return shifted.toISOString().slice(0, 10)
}

/**
 * A `sitting_date` (`YYYY-MM-DD`) as "mardi 2 septembre 2026".
 *
 * Parsed as UTC midnight and formatted in UTC - the value is already a plain
 * calendar date the API grouped by, so converting it to a zone would shift it.
 */
export function formatSittingDay(isoDate: string, opts?: { withYear?: boolean }): string {
  const date = new Date(`${isoDate}T00:00:00Z`)
  if (Number.isNaN(date.getTime())) return isoDate
  const formatted = (opts?.withYear === false ? SHORT_DAY : LONG_DAY).format(date)
  // Only the weekday is capitalized: CSS `text-transform: capitalize` would
  // also capitalize the month, which French does not.
  return formatted.charAt(0).toUpperCase() + formatted.slice(1)
}

/** A `sitting_start` timestamp as the Paris wall-clock time, e.g. `15h00`. */
export function formatSittingTime(timestamp: string | null | undefined): string | null {
  if (!timestamp) return null
  const date = new Date(timestamp)
  if (Number.isNaN(date.getTime())) return null
  return TIME.format(date).replace(':', 'h')
}

/**
 * The citizen-summary-first hierarchy MON-89 established for vote cards.
 *
 * `summary_plain` is generated by MON-211, which has not shipped, and is NULL
 * by design for stub `objet`s even once it has - so the official wording is
 * the lead whenever there is no one-liner, never an empty slot above it.
 */
export function agendaHeadline(item: Pick<AgendaItem, 'summary_plain' | 'objet'>): {
  lead: string
  official: string | null
} {
  const summary = item.summary_plain?.trim()
  const objet = item.objet?.trim()
  if (summary) return { lead: summary, official: objet || null }
  if (objet) return { lead: objet, official: null }
  return { lead: 'Point inscrit à l’ordre du jour', official: null }
}

/**
 * Is `point_type` worth printing next to the headline?
 *
 * A large share of ODJ points carry an `objet` that is a bare stub identical
 * to the point type - "Discussion", "Questions au Gouvernement" - which the
 * schema comment on `agenda_items.objet` already warns about. Printing both
 * gives the row the same word twice and no extra information.
 */
export function showsPointType(pointType: string | null | undefined, lead: string): boolean {
  if (!pointType?.trim()) return false
  return pointType.trim().toLowerCase() !== lead.trim().toLowerCase()
}

/**
 * Does this item say anything a reader could not have guessed from the slot?
 *
 * The homepage teaser has room for three lines and only one chance to be
 * interesting; a stub-only day would spend all three on the word "Discussion".
 * `/agenda` shows everything regardless - completeness is the point there.
 */
export function isSubstantive(
  item: Pick<AgendaItem, 'summary_plain' | 'objet' | 'point_type'>
): boolean {
  if (item.summary_plain?.trim()) return true
  const objet = item.objet?.trim()
  if (!objet) return false
  // No point type to duplicate: whatever the objet says is all we have.
  if (!item.point_type?.trim()) return true
  return showsPointType(item.point_type, objet)
}

/** Where an item points: its scrutin once one exists, else the AN dossier. */
export function agendaItemHref(item: Pick<AgendaItem, 'vote_id' | 'dossier_url'>): string | null {
  if (item.vote_id) return `/votes/${item.vote_id}`
  return item.dossier_url ?? null
}
