// Theme slug <-> name map, mirroring api/themes_data.py.
// The taxonomy itself (10 fixed categories) is generated by
// scripts/generate_vote_summaries.py — this file only adds a stable URL
// slug per theme, matching the VotesClient THEMES list.
const THEME_NAMES: Record<string, string> = {
  'economie-budget': 'Économie & Budget',
  'sante-social': 'Santé & Social',
  'justice-securite': 'Justice & Sécurité',
  'energie-environnement': 'Énergie & Environnement',
  'education-culture': 'Éducation & Culture',
  'agriculture': 'Agriculture',
  'transport-logement': 'Transport & Logement',
  'institutions': 'Institutions',
  'international': 'International',
  'autre': 'Autre',
}

const SLUGS_BY_NAME = new Map(
  Object.entries(THEME_NAMES).map(([slug, name]) => [name, slug])
)

/** All (slug, name) pairs, in the same order as VotesClient's THEMES list. */
export const THEME_ENTRIES: Array<{ slug: string; name: string }> = Object.entries(
  THEME_NAMES
).map(([slug, name]) => ({ slug, name }))

/** Canonical theme name for a slug, or null if unknown. */
export function themeName(slug: string): string | null {
  return THEME_NAMES[slug.trim().toLowerCase()] ?? null
}

/** URL slug for a theme name, or null if unknown. */
export function themeSlug(name: string | null | undefined): string | null {
  if (!name) return null
  return SLUGS_BY_NAME.get(name) ?? null
}
